# Generated by Django 2.0.2 on 2018-03-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('heading', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=10000)),
            ],
        ),
    ]
